FROM golang:1.22.5-bookworm AS builder

WORKDIR /app
COPY . .
RUN go mod download
ENV CGO_ENABLED=1


RUN go build -o web /app/cmd/web




FROM alpine:edge

WORKDIR /app

COPY --from=builder /app/web /app/
COPY  ./tls/ /app/tls/
COPY  ./articles.sqlite /app/
EXPOSE 443
CMD /app/web

